import { defineField, defineType } from 'sanity'

export default defineType({
  name: 'propFirm',
  title: 'Prop Firm',
  type: 'document',
  groups: [
    { name: 'core', title: 'Core (PID)', default: true },
    { name: 'research', title: 'Research Data' },
  ],
  fields: [
    // ---- Core PID model (matches live 6hyvhmum documents) ----
    defineField({ name: 'name', title: 'Firm Name', type: 'string', validation: (Rule) => Rule.required(), group: 'core' }),
    defineField({ name: 'slug', title: 'Slug', type: 'slug', options: { source: 'name' }, validation: (Rule) => Rule.required(), group: 'core' }),
    defineField({ name: 'pidId', title: 'PID', type: 'string', description: 'Stable PID key, e.g. "apex"', group: 'core' }),
    defineField({ name: 'ticker', title: 'Ticker / Abbreviation', type: 'string', group: 'core' }),
    defineField({ name: 'logo', title: 'Logo', type: 'image', options: { hotspot: true }, group: 'core' }),
    defineField({ name: 'website', title: 'Website', type: 'url', group: 'core' }),
    defineField({ name: 'country', title: 'Country', type: 'string', group: 'core' }),
    defineField({ name: 'affiliateCode', title: 'Affiliate Code', type: 'string', description: 'e.g. MOT / MIGHTYOX', group: 'core' }),
    defineField({ name: 'description', title: 'Short Description', type: 'text', rows: 3, group: 'core' }),
    defineField({ name: 'dataStatus', title: 'Data Status', type: 'string', options: { list: ['verified', 'partial', 'unverified'] }, group: 'core' }),
    defineField({ name: 'lastVerified', title: 'Last Verified', type: 'date', group: 'core' }),
    defineField({ name: 'sourceIds', title: 'Source IDs', type: 'string', description: 'Semicolon-separated SRC registry refs', group: 'core' }),
    defineField({ name: 'plans', title: 'Available Plans', type: 'array', of: [{ type: 'reference', to: { type: 'plan' } }], group: 'core' }),
    // ---- Research layer (Jul 2026 firm-level dataset) ----
    defineField({ name: 'trustPilotRating', title: 'Trust Pilot Rating', type: 'string', group: 'research' }),
    defineField({ name: 'ceo', title: 'CEO', type: 'string', group: 'research' }),
    defineField({ name: 'countryOfOrigin', title: 'Country Of Origin (detail)', type: 'string', group: 'research' }),
    defineField({ name: 'yearFounded', title: 'Year Founded', type: 'string', group: 'research' }),
    defineField({ name: 'highlight', title: 'Highlight', type: 'text', rows: 2, group: 'research' }),
    defineField({ name: 'accountTypes', title: 'Account Types', type: 'string', group: 'research' }),
    defineField({ name: 'accountSizes', title: 'Account Sizes', type: 'string', group: 'research' }),
    defineField({ name: 'daysToPass', title: 'Days To Pass', type: 'string', group: 'research' }),
    defineField({ name: 'maxAllocation', title: 'Max Allocation', type: 'string', group: 'research' }),
    defineField({ name: 'maxFundedAccounts', title: 'Max Funded Accounts', type: 'string', group: 'research' }),
    defineField({ name: 'profitSplit', title: 'Profit Split', type: 'string', group: 'research' }),
    defineField({ name: 'payoutWindow', title: 'Payout Window', type: 'string', group: 'research' }),
    defineField({ name: 'payoutFrequency', title: 'Payout Frequency', type: 'string', group: 'research' }),
    defineField({ name: 'payoutMethods', title: 'Payout Methods', type: 'string', group: 'research' }),
    defineField({ name: 'supportChannels', title: 'Support Channels', type: 'string', group: 'research' }),
    defineField({ name: 'paymentsAccepted', title: 'Payments Accepted', type: 'string', group: 'research' }),
    defineField({ name: 'platformsUsed', title: 'Platforms Used', type: 'string', group: 'research' }),
    defineField({ name: 'commissions', title: 'Commissions', type: 'string', group: 'research' }),
    defineField({ name: 'consistency', title: 'Consistency', type: 'string', group: 'research' }),
    defineField({ name: 'tradingStrategyStyle', title: 'Trading Strategy & Style', type: 'text', rows: 2, group: 'research' }),
    defineField({ name: 'miscellaneous', title: 'Miscellaneous', type: 'text', rows: 2, group: 'research' }),
    defineField({ name: 'dataTier', title: 'Research Tier', type: 'string', options: { list: ['A', 'B'] }, group: 'research' }),
    defineField({ name: 'researchDate', title: 'Research Date', type: 'date', group: 'research' }),
  ],
  preview: {
    select: { title: 'name', subtitle: 'ticker' },
  },
})
